# Project
version=1.3.3
group=net.bivrik
java_version=21

# Common
mod_name=FancyToasts
mod_author=Bivrik
mod_id=fancytoasts
license=MIT
credits=My friends and everyone who downloaded so far! <3
description=Redesigns the old advancement toast system, replacing it with a more attractive and interesting one.
issue_tracker_url=https://github.com/Bivrik/FancyToasts/issues
homepage_url=https://github.com/Bivrik
sources_url=https://github.com/Bivrik/FancyToasts

# Minecraft
minecraft_version=1.21.6
minecraft_version_range=[1.21.6, 1.22)

# Neoform thingy. See https://maven.neoforged.net/releases/net/neoforged/neoform for new versions
neo_form_version=1.21.6-20250617.151856

# ParchmentMC. See https://ldtteam.jfrog.io/ui/native/parchmentmc-public/org/parchmentmc/data for new versions
parchment_minecraft=1.21.6
parchment_version=2025.06.29

# Fabric. See https://fabricmc.net/develop/ for new versions
fabric_version=0.128.2+1.21.6
fabric_loader_version=0.17.2
# See https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu for new versions
fabric_modmenu_version=15.0.0-beta.3

# Forge. See https://files.minecraftforge.net/net/minecraftforge/forge for new versions
forge_version=56.0.9
forge_loader_version_range=[55,)

# NeoForge. See https://neoforged.net for new versions
neoforge_version=21.6.20-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
